-- Self-contained database baseline — authoritative CREATE TABLE source for
-- the platform's foundational schema (profiles, businesses,
-- knowledge_items, conversations, messages, leads, handoffs,
-- widget_settings), which until now existed only in the older, external
-- ChatbotDemo project. This repository's own migrations
-- (supabase/migrations/20260915000100_platform_onboarding.sql onward)
-- have always assumed these eight tables already exist and only ever
-- ADD to them (columns, policies, indexes) — none of them create the
-- tables themselves. A brand-new, empty Supabase project therefore could
-- not run this repository's migration history from beginning to end.
-- This migration is what makes it able to.
--
-- Ordering: timestamped 20260910090000 — before every other file in this
-- directory (the earliest existing migration is
-- 20260915000100_platform_onboarding.sql) — so it runs first against a
-- blank database, and every later migration's own `alter table ... add
-- column if not exists` / `create policy` / `create index if not exists`
-- statements find the table they expect already in place.
--
-- SCOPE — deliberately narrow. This migration creates each of the eight
-- tables in the shape they had BEFORE this repository's own additive
-- migrations touched them, and nothing more:
--   - profiles: WITHOUT onboarding_completed / onboarding_completed_at
--     (added by 20260915000100_platform_onboarding.sql)
--   - businesses: WITHOUT the businesses_owner_id_key unique index
--     (added by 20260921090000_single_business_per_owner.sql)
--   - messages: WITHOUT sender_type / client_message_id
--     (added by 20260915170200_inbox_human_replies.sql)
--   - widget_settings: WITHOUT widget_enabled / allowed_origins (added by
--     20260916120000_widget_allowed_origins.sql) and WITHOUT
--     installation_confirmed / installation_confirmed_at (added by
--     20260917140000_widget_installation_confirmed.sql)
--   - handoffs: WITHOUT client_request_id
--     (added by 20260918090000_handoff_idempotency.sql)
--   - knowledge_items, conversations, leads: unchanged by any later
--     migration in this repo, so their shape here is already final.
-- Every one of those later migrations already uses `add column if not
-- exists` / `create index if not exists` / `create policy` (drop-then-
-- create), so running them against the tables this migration creates
-- converges on exactly the same end state as running them against the
-- real, existing ChatbotDemo-created tables in production. This
-- migration intentionally does NOT create any of those later objects
-- itself — see "Not duplicate objects created by later migrations" below.
--
-- EVIDENCE — every column, type, and constraint below is derived from
-- one or more of:
--   (a) this repository's own later migrations, which document a
--       column's existence, type, or a lookup key's uniqueness in their
--       own header comments or `alter table` statements (cited inline
--       below, migration by migration);
--   (b) src/lib/supabase/database.types.ts, this repository's own
--       hand-written row types for the shared schema, which its own
--       header comment describes as ported from ChatbotDemo's real
--       migrations and required to stay in sync with them;
--   (c) a repository-wide audit of every `.from('<table>')` call in
--       src/**, cross-checking every `.select()`/`.insert()`/`.update()`/
--       `.eq()`/`.order()` against (a) and (b) — confirming no column is
--       used that isn't already known, confirming which lookups assume
--       uniqueness (via `.maybeSingle()`/`.single()` after filtering on
--       exactly one column), which columns are always supplied on
--       insert vs. always omitted (implying a required database
--       default), and every literal value ever written to an enum-like
--       text column (cross-checked against the type unions in (b)).
-- See this migration's own PR/report for the full evidence trail.
--
-- UNCERTAIN / NOT PROVABLE FROM THIS REPOSITORY — called out here, not
-- guessed silently:
--   - businesses.slug: never queried anywhere in src/** (write-only,
--     always generated by handle_new_user() as
--     'business-' || <fresh uuid, dashes stripped>, which is unique by
--     construction). No application code assumes slug is a unique
--     lookup key. This migration still adds a unique index — a bare
--     "slug" column is conventionally expected to be unique, and the
--     one value this repository ever writes into it is already globally
--     unique by construction, so the index can never reject a real
--     write this app makes — but this is this migration's own inference
--     from naming convention, not a fact independently confirmed
--     against ChatbotDemo's real schema.
--   - leads.reference: explicitly documented in this repo's own
--     src/lib/public-widget/runtime.ts (generateLeadReference() doc
--     comment) as "a short, human-scannable reference, not a security
--     token ... has no known uniqueness requirement this needs to
--     defend against beyond 'very unlikely to collide'" — no application
--     code ever looks it up by value. This migration therefore does NOT
--     add a unique constraint on it, matching that documented intent
--     exactly rather than guessing one into existence.
--   - Foreign-key ON DELETE behavior (owner_id/business_id/
--     conversation_id) is not provable from any migration or query in
--     this repository (nothing in this app ever deletes a business,
--     conversation, or auth user today). This migration uses
--     `on delete cascade` for owner_id -> auth.users and business_id ->
--     businesses — the same choice this repo's own
--     20260920100000_paddle_billing_foundation.sql already made for
--     business_subscriptions.business_id and billing_checkout_
--     attempts.business_id, so this migration is at least internally
--     consistent with this repo's own established precedent — and
--     `on delete set null` for the nullable conversation_id references
--     on leads/handoffs (never cascade a delete through a nullable
--     reference onto rows that stand on their own). None of this is
--     exercised by any feature that exists today.
--   - A working `updated_at` column requires *something* to advance it
--     on every UPDATE — no migration or application code ever sets
--     `updated_at` explicitly (confirmed by the same repo-wide audit;
--     see e.g. src/features/inbox/api/service.ts's own
--     `.order('updated_at', { ascending: false })` for the Inbox list,
--     which only makes sense if the column tracks real recency), so
--     this migration adds one `set_updated_at()` trigger function plus
--     one `BEFORE UPDATE` trigger per table that has the column, all
--     under names owned exclusively by this migration
--     (`set_updated_at_<table>`) so they can never collide with or
--     replace a same-purpose trigger already installed under some other
--     name in production — worst case, both fire and reach the same
--     result. This mechanism itself is inferred, not confirmed against
--     ChatbotDemo's real implementation.
--
-- EXISTING-DATABASE SAFETY — `create table if not exists` alone silently
-- accepts an incompatible pre-existing table (the exact failure mode
-- this repo's own 20260920100000_paddle_billing_foundation.sql hit in
-- production: `ERROR 42703: column "paddle_price_id" ... does not
-- exist`, because `create table if not exists` never retrofits a column
-- onto a table that already existed under that name). This migration
-- never assumes a same-named pre-existing table is compatible: after
-- each `create table if not exists`, a DO block checks that every column
-- this migration (and every later migration that assumes it) needs is
-- actually present, and that the table has a primary key, using
-- information_schema/pg_catalog only — never row contents. A pre-
-- existing, incompatible table fails loudly with a fixed, generic
-- exception naming only the table/column contract, never row values,
-- business IDs, user IDs, or customer data. This migration never
-- attempts to "repair" an incompatible table itself (add a missing
-- column, change a type) — that is a separate, explicit, verified
-- follow-up migration a human reviews first.
--
-- Never touches auth.users itself (no ALTER, no ownership/permission
-- change) beyond the ordinary, Supabase-permitted `references
-- auth.users(id)` foreign keys on profiles.id and businesses.owner_id —
-- the same kind of reference every Supabase starter schema uses, and no
-- different in kind from every other `references public.businesses(id)`
-- foreign key elsewhere in this same migration.
--
-- Not duplicate objects created by later migrations: this migration
-- creates each of the eight tables with Row Level Security ENABLED and
-- ZERO policies — exactly the state 20260915193000_repair_live_rls_
-- policies.sql's own header comment documents finding in a live audit of
-- production ("businesses: 0 conversations: 0 ... widget_settings: 0")
-- before it ran. All owner-scoped policies for these tables already
-- exist as idempotent `drop policy if exists` + `create policy` pairs in
-- that migration and in 20260915184700_knowledge_items_owner_policies.sql
-- — this migration deliberately does not re-declare any of them, so
-- there is exactly one place in this repository that owns each policy's
-- SQL. Table-level SELECT/INSERT/UPDATE/DELETE privileges for `anon`/
-- `authenticated` are governed by this Supabase project's own default
-- privileges (the same reason no other migration in this repo grants
-- table-level access to profiles/businesses/etc. either) — RLS is what
-- actually restricts row access once those default privileges apply.
-- This migration also never creates businesses_owner_id_key,
-- messages_client_message_id_key, widget_settings.widget_enabled/
-- allowed_origins/installation_confirmed(_at), or handoffs.
-- client_request_id — all already owned by their own later migrations,
-- listed in SCOPE above.
--
-- Never deletes, truncates, or rewrites any existing row; never renames
-- or silently changes an existing column's type; never weakens,
-- disables, or drops any RLS policy, grant, index, constraint, or
-- trigger; contains no real user data, emails, business IDs, or secrets
-- anywhere, including in comments and identifiers.

-- =====================================================================
-- 0. Shared helper: set_updated_at(). One trigger function, reused by a
--    per-table BEFORE UPDATE trigger below. See the "UNCERTAIN" note
--    above for why this migration adds it at all.
-- =====================================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Shared BEFORE UPDATE trigger function: stamps updated_at = now() on every row update. Installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql for every foundational table with an updated_at column — see that migration''s own header comment for why.';

-- =====================================================================
-- 1. profiles — one row per auth.users row, keyed by the same id.
--    Columns/shape confirmed by: src/lib/supabase/database.types.ts
--    (ProfileRow, minus onboarding_completed/onboarding_completed_at,
--    which 20260915000100_platform_onboarding.sql's own header comment
--    documents as new additive columns it introduces); profiles.id as
--    the FK to auth.users is confirmed by
--    20260915193000_repair_live_rls_policies.sql's own policies
--    (`id = auth.uid()`) and by every `.eq('id', <user id>)` call in
--    src/features/auth/components/signup-form.tsx and
--    src/features/onboarding/api/service.ts.
-- =====================================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array['id', 'display_name', 'created_at', 'updated_at']) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.profiles already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'profiles' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.profiles already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

alter table public.profiles enable row level security;

drop trigger if exists set_updated_at_profiles on public.profiles;
create trigger set_updated_at_profiles
  before update on public.profiles
  for each row
  execute function public.set_updated_at();

comment on table public.profiles is
  'One row per signed-up account. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see supabase/migrations/20260915000100_platform_onboarding.sql for this table''s additive post-signup onboarding-tracking columns and 20260922090000_self_contained_user_provisioning.sql for the trigger that populates this table on signup.';

-- =====================================================================
-- 2. businesses — one row per business; owner_id links to the owning
--    auth.users row. Columns/shape confirmed by database.types.ts
--    (BusinessRow) and by the exact column list
--    20260922090000_self_contained_user_provisioning.sql's own
--    handle_new_user() inserts:
--      id, owner_id, name, slug, public_widget_id, business_type,
--      location, default_language, supported_languages, handoff_email,
--      is_active
--    public_widget_id's uniqueness is confirmed by
--    src/lib/public-widget/runtime.ts's resolveWidgetForRuntime(),
--    which looks it up via `.eq('public_widget_id', ...).maybeSingle()`
--    — a hard assumption that at most one business row can ever match.
--    owner_id's own uniqueness (businesses_owner_id_key) is
--    deliberately NOT created here — see SCOPE above; that index
--    belongs to 20260921090000_single_business_per_owner.sql alone.
-- =====================================================================
create table if not exists public.businesses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users (id) on delete cascade,
  name text not null,
  slug text not null,
  public_widget_id uuid not null default gen_random_uuid(),
  business_type text not null,
  location text,
  default_language text not null default 'en',
  supported_languages text[] not null default array['en'],
  handoff_email text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array[
    'id', 'owner_id', 'name', 'slug', 'public_widget_id', 'business_type',
    'location', 'default_language', 'supported_languages', 'handoff_email',
    'is_active', 'created_at', 'updated_at'
  ]) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'businesses' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.businesses already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'businesses' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.businesses already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

-- Pre-check before each unique index below, same pattern as
-- 20260921090000_single_business_per_owner.sql's own owner_id check:
-- raise a clear diagnostic naming only the count/value, never any other
-- row data, rather than a bare unique-violation error or a silent skip.
do $$
declare
  v_dup_count integer;
begin
  select count(*) into v_dup_count
  from (
    select public_widget_id from public.businesses
    group by public_widget_id having count(*) > 1
  ) dupes;
  if v_dup_count > 0 then
    raise exception
      'public.businesses has % public_widget_id value(s) shared by more than one row — a unique public_widget_id index cannot be safely applied while duplicates exist. Resolve in a verified follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      v_dup_count;
  end if;
end $$;

create unique index if not exists businesses_public_widget_id_key
  on public.businesses (public_widget_id);

do $$
declare
  v_dup_count integer;
begin
  select count(*) into v_dup_count
  from (
    select slug from public.businesses
    group by slug having count(*) > 1
  ) dupes;
  if v_dup_count > 0 then
    raise exception
      'public.businesses has % slug value(s) shared by more than one row — a unique slug index cannot be safely applied while duplicates exist. Resolve in a verified follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      v_dup_count;
  end if;
end $$;

create unique index if not exists businesses_slug_key
  on public.businesses (slug);

alter table public.businesses enable row level security;

drop trigger if exists set_updated_at_businesses on public.businesses;
create trigger set_updated_at_businesses
  before update on public.businesses
  for each row
  execute function public.set_updated_at();

comment on table public.businesses is
  'One row per business. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see 20260921090000_single_business_per_owner.sql for the additive owner_id uniqueness constraint and 20260922090000_self_contained_user_provisioning.sql for the trigger that populates this table on signup.';

-- =====================================================================
-- 3. knowledge_items — FAQ-style entries scoped to a business. Columns
--    confirmed by database.types.ts (KnowledgeItemRow) and by
--    src/features/knowledge/api/service.ts's own INSERT (supplies
--    business_id, category, question, answer_en, answer_me, answer_ru,
--    is_active, sort_order — every one of those explicitly, every time)
--    and its list query's `.eq('business_id', ...).order('sort_order',
--    { ascending: true }).order('created_at', { ascending: true })`.
-- =====================================================================
create table if not exists public.knowledge_items (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  category text not null,
  question text not null,
  answer_en text not null,
  answer_me text,
  answer_ru text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array[
    'id', 'business_id', 'category', 'question', 'answer_en', 'answer_me',
    'answer_ru', 'is_active', 'sort_order', 'created_at', 'updated_at'
  ]) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'knowledge_items' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.knowledge_items already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'knowledge_items' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.knowledge_items already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

create index if not exists knowledge_items_business_id_sort_order_created_at_idx
  on public.knowledge_items (business_id, sort_order, created_at);

alter table public.knowledge_items enable row level security;

drop trigger if exists set_updated_at_knowledge_items on public.knowledge_items;
create trigger set_updated_at_knowledge_items
  before update on public.knowledge_items
  for each row
  execute function public.set_updated_at();

comment on table public.knowledge_items is
  'FAQ-style knowledge base entries scoped to a business, used both by the owner-facing dashboard and the AI receptionist''s own reply matching. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see 20260915184700_knowledge_items_owner_policies.sql for its owner-scoped RLS policies.';

-- =====================================================================
-- 4. conversations — one row per visitor conversation with a business's
--    widget. Columns confirmed by database.types.ts (ConversationRow)
--    and by src/lib/public-widget/runtime.ts's own INSERT (supplies
--    business_id, visitor_id, channel, detected_language, status,
--    human_takeover, lead_created, flow_state) and
--    src/features/inbox/api/service.ts's
--    `.order('updated_at', { ascending: false })` Inbox-list query.
--    Enum values (channel/status) cross-checked against every literal
--    actually written anywhere in src/**: channel only ever writes
--    'website' (instagram/whatsapp exist in the type union but no
--    insert path uses them yet); status writes 'open'/'closed'/
--    'handed_off', matching ConversationStatus exactly.
-- =====================================================================
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  visitor_id text not null,
  channel text not null default 'website',
  detected_language text not null default 'en',
  status text not null default 'open',
  human_takeover boolean not null default false,
  lead_created boolean not null default false,
  flow_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_channel_check check (channel in ('website', 'instagram', 'whatsapp')),
  constraint conversations_status_check check (status in ('open', 'closed', 'handed_off'))
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array[
    'id', 'business_id', 'visitor_id', 'channel', 'detected_language',
    'status', 'human_takeover', 'lead_created', 'flow_state', 'created_at',
    'updated_at'
  ]) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'conversations' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.conversations already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'conversations' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.conversations already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

create index if not exists conversations_business_id_updated_at_idx
  on public.conversations (business_id, updated_at desc);

alter table public.conversations enable row level security;

drop trigger if exists set_updated_at_conversations on public.conversations;
create trigger set_updated_at_conversations
  before update on public.conversations
  for each row
  execute function public.set_updated_at();

comment on table public.conversations is
  'One row per visitor conversation with a business''s widget. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see 20260915193000_repair_live_rls_policies.sql for its owner-scoped RLS policies.';

-- =====================================================================
-- 5. messages — one row per message within a conversation. Columns
--    confirmed by database.types.ts (MessageRow, minus sender_type/
--    client_message_id, which 20260915170200_inbox_human_replies.sql's
--    own header comment documents as its own additive columns) and by
--    every `.insert()` into messages in src/lib/public-widget/
--    runtime.ts (always supplies conversation_id, role, content; never
--    id or created_at). No updated_at column — this table has none in
--    database.types.ts's MessageRow, and no code anywhere reads or
--    writes one. Role values cross-checked: 'user'/'assistant' are
--    written; 'system' exists only in the type union, never written by
--    any code path today.
-- =====================================================================
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  role text not null,
  content text not null,
  intent text,
  created_at timestamptz not null default now(),
  constraint messages_role_check check (role in ('user', 'assistant', 'system'))
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array[
    'id', 'conversation_id', 'role', 'content', 'intent', 'created_at'
  ]) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'messages' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.messages already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'messages' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.messages already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

create index if not exists messages_conversation_id_created_at_idx
  on public.messages (conversation_id, created_at);

alter table public.messages enable row level security;

comment on table public.messages is
  'One row per message within a conversation. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see 20260915170200_inbox_human_replies.sql for this table''s additive Inbox-related columns and its owner-facing insert policy, and 20260915193000_repair_live_rls_policies.sql for the SELECT/DELETE owner policies.';

-- =====================================================================
-- 6. leads — captured booking/contact leads scoped to a business, with
--    an optional link back to the conversation that produced them.
--    Columns confirmed by database.types.ts (LeadRow) and by
--    src/lib/public-widget/runtime.ts's own INSERT (supplies
--    business_id, conversation_id, reference, name, contact, check_in,
--    check_out, guest_count, note, language, source, status,
--    consent_at). check_in/check_out are date-only (never time-of-day)
--    per src/features/leads/api/service.test.ts's own fixture values
--    ('2026-08-14'). reference is deliberately NOT unique-constrained —
--    see the UNCERTAIN note in this migration's own header comment.
--    Enum values (source/status) cross-checked against every literal
--    written anywhere in src/**: source only ever writes 'website';
--    status writes only 'new' on insert (owner-driven status changes
--    use the full LeadStatus union server-side, but no literal beyond
--    'new'/'contacted'/'confirmed'/'lost' — the full known set — appears
--    anywhere).
-- =====================================================================
create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  conversation_id uuid references public.conversations (id) on delete set null,
  reference text not null,
  name text not null,
  contact text not null,
  check_in date,
  check_out date,
  guest_count integer,
  note text,
  language text not null default 'en',
  source text not null default 'website',
  status text not null default 'new',
  consent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leads_source_check check (source in ('website', 'instagram', 'whatsapp')),
  constraint leads_status_check check (status in ('new', 'contacted', 'confirmed', 'lost'))
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array[
    'id', 'business_id', 'conversation_id', 'reference', 'name', 'contact',
    'check_in', 'check_out', 'guest_count', 'note', 'language', 'source',
    'status', 'consent_at', 'created_at', 'updated_at'
  ]) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'leads' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.leads already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'leads' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.leads already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

create index if not exists leads_business_id_created_at_idx
  on public.leads (business_id, created_at desc);

create index if not exists leads_conversation_id_created_at_idx
  on public.leads (conversation_id, created_at desc);

alter table public.leads enable row level security;

drop trigger if exists set_updated_at_leads on public.leads;
create trigger set_updated_at_leads
  before update on public.leads
  for each row
  execute function public.set_updated_at();

comment on table public.leads is
  'Captured booking/contact leads scoped to a business. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see 20260915193000_repair_live_rls_policies.sql for its owner-scoped RLS policies. reference has no uniqueness constraint by design — see this migration''s own header comment.';

-- =====================================================================
-- 7. handoffs — human-handoff requests scoped to a business, with an
--    optional link back to the conversation that produced them. Columns
--    confirmed by database.types.ts (HandoffRow, minus
--    client_request_id, which 20260918090000_handoff_idempotency.sql's
--    own header comment documents as its own additive column) and by
--    src/lib/public-widget/runtime.ts's own INSERT (supplies
--    business_id, conversation_id, customer_name, contact, question,
--    status; reason is never set by any code path). Enum values
--    (status) cross-checked: 'new'/'contacted'/'resolved' are all
--    written somewhere in src/**, matching HandoffStatus exactly.
-- =====================================================================
create table if not exists public.handoffs (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  conversation_id uuid references public.conversations (id) on delete set null,
  customer_name text,
  contact text not null,
  question text,
  reason text,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint handoffs_status_check check (status in ('new', 'contacted', 'resolved'))
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array[
    'id', 'business_id', 'conversation_id', 'customer_name', 'contact',
    'question', 'reason', 'status', 'created_at', 'updated_at'
  ]) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'handoffs' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.handoffs already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'handoffs' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.handoffs already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

create index if not exists handoffs_business_id_created_at_idx
  on public.handoffs (business_id, created_at desc);

create index if not exists handoffs_conversation_id_created_at_idx
  on public.handoffs (conversation_id, created_at desc);

alter table public.handoffs enable row level security;

drop trigger if exists set_updated_at_handoffs on public.handoffs;
create trigger set_updated_at_handoffs
  before update on public.handoffs
  for each row
  execute function public.set_updated_at();

comment on table public.handoffs is
  'Human-handoff requests scoped to a business. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see 20260918090000_handoff_idempotency.sql for this table''s additive idempotency-key column and 20260915193000_repair_live_rls_policies.sql for its owner-scoped RLS policies.';

-- =====================================================================
-- 8. widget_settings — at most one row per business, holding the public
--    widget's display configuration. Columns confirmed by
--    database.types.ts (WidgetSettingsRow, minus widget_enabled/
--    allowed_origins/installation_confirmed(_at), each documented as
--    additive by its own later migration — see SCOPE above) and by the
--    exact column list 20260922090000_self_contained_user_provisioning.
--    sql's own handle_new_user() inserts:
--      business_id, title, welcome_message_en, welcome_message_me,
--      welcome_message_ru, primary_color, position, mock_ai_enabled,
--      widget_enabled, human_handoff_enabled, allowed_origins,
--      installation_confirmed
--    (the last three of those belong to later migrations per SCOPE
--    above, but that INSERT already only runs after all of this
--    repository's migrations have applied in order, so it is
--    unaffected). business_id's uniqueness is confirmed by four
--    separate `.eq('business_id', ...).maybeSingle()` call sites across
--    src/lib/public-widget/runtime.ts, src/features/widget/api/
--    service.ts, src/app/dashboard/overview/page.tsx, and
--    src/app/onboarding/page.tsx — every one of them assumes at most one
--    widget_settings row exists per business.
-- =====================================================================
create table if not exists public.widget_settings (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses (id) on delete cascade,
  title text not null default '',
  welcome_message_en text,
  welcome_message_me text,
  welcome_message_ru text,
  primary_color text not null default '#1677ff',
  "position" text not null default 'bottom-right',
  mock_ai_enabled boolean not null default true,
  human_handoff_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint widget_settings_position_check check ("position" in ('bottom-right', 'bottom-left'))
);

do $$
declare
  v_missing text[];
begin
  select array_agg(col) into v_missing
  from unnest(array[
    'id', 'business_id', 'title', 'welcome_message_en', 'welcome_message_me',
    'welcome_message_ru', 'primary_color', 'position', 'mock_ai_enabled',
    'human_handoff_enabled', 'created_at', 'updated_at'
  ]) as col
  where not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'widget_settings' and column_name = col
  );
  if v_missing is not null then
    raise exception
      'public.widget_settings already exists but is missing required column(s): %. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      array_to_string(v_missing, ', ');
  end if;

  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'widget_settings' and constraint_type = 'PRIMARY KEY'
  ) then
    raise exception
      'public.widget_settings already exists but has no primary key. Resolve this schema mismatch in a verified, explicit follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.';
  end if;
end $$;

do $$
declare
  v_dup_count integer;
begin
  select count(*) into v_dup_count
  from (
    select business_id from public.widget_settings
    group by business_id having count(*) > 1
  ) dupes;
  if v_dup_count > 0 then
    raise exception
      'public.widget_settings has % business_id value(s) shared by more than one row — a unique business_id index cannot be safely applied while duplicates exist. Resolve in a verified follow-up migration before rerunning supabase/migrations/20260910090000_self_contained_database_baseline.sql.',
      v_dup_count;
  end if;
end $$;

create unique index if not exists widget_settings_business_id_key
  on public.widget_settings (business_id);

alter table public.widget_settings enable row level security;

drop trigger if exists set_updated_at_widget_settings on public.widget_settings;
create trigger set_updated_at_widget_settings
  before update on public.widget_settings
  for each row
  execute function public.set_updated_at();

comment on table public.widget_settings is
  'At most one row per business (widget_settings_business_id_key), holding the public widget''s display configuration. Baseline shape installed by supabase/migrations/20260910090000_self_contained_database_baseline.sql — see this table''s later, chronologically-numbered migrations for its additive columns, and 20260915193000_repair_live_rls_policies.sql for its owner-scoped RLS policies.';
